### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by Stevesuk0** [Fluxyn/PyModMC#2]
This project is awesome, is it currently in production?

**Comment by Fluxyn** [comment]
I haven’t made a commit in over a year but I can definitely add to this project. Was there anything in mind that you wanted me to add?

**Comment by Stevesuk0** [comment]
It's like defining in-game commands, calling&nbsp;python code with in-game commands or something like that&nbsp;


成长的足迹
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年7月24日(星期一) 凌晨0:39
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [Fluxyn/PyModMC] wow (Issue #2)





 
I haven’t made a commit in over a year but I can definitely add to this project. Was there anything in mind that you wanted me to add?
