### ISSUE TITLE
Fabric doesn't work with my First Test Mod

### ISSUE THREAD

**Issue by Kaktus000** [Fluxyn/PyModMC#8]
I created A first test Mod to test out PyModMc but when I tried to launch Fabric 1.21.4 i got a error:

Fabric Error:
    Incompatible mods found!
    net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
    A potential solution has been determined, this may resolve your problem:
	 - Install fabric-api, any version.
    More details:
	 - Mod 'Test Mod' (testmod) 0.0.1 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

other mods installed:
  -Iris
  -Sodium

my python program I used to Build it:
`from PyModMC import *
test_mod = Mod('Test Mod', '0.0.1', 'A test mod.', '1.21.4', ['XNeedNoName'])
FoodItem(test_mod, 'Donut', 1, 1, image="donut.png")
test_mod.build()`
a change i did in the PyModMC code cause i got a error with shutil.copyfile (lines 354 - 356 in main.py):
`        jar_file = os.path.join(self.mod_folder, 'build', 'libs', self.modid + '-' + self.mod_version + '.jar')
        direction = os.path.join(self.directory, self.modid + '-' + self.mod_version + '.jar')
        shutil.copyfile(jar_file, direction)`
sorry for the bad indentation and missing newlines i'm new to github and don't know how to do it.

**Comment by Fluxyn** [comment]
Sorry, but I haven't been working on this in years and I would say that it's pretty much deprecated and broken. I have had some new ideas for an upcoming project though.
